server.port=8082
spring.application.name=dietapp

# The API Key (Ensure there are no spaces after the =)
langchain4j.open-ai.chat-model.api-key=sk-f1969109c980bb53a9099126d7ae67bab423753f46bec74c
langchain4j.open-ai.chat-model.model-name=gpt-4o

# YOU MUST UNCOMMENT THIS (Remove the #) for the Ysk key to work!
#langchain4j.open-ai.chat-model.base-url=https://api.ilmu.ai/v1